# Generated by Django 5.2.5 on 2025-08-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
