# Generated by Django 5.2.5 on 2025-08-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_blogpost_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
    ]
