# Generated by Django 5.2.5 on 2025-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_navigationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
