# Generated by Django 5.2.5 on 2025-08-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_pagesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageSection',
        ),
    ]
