# Generated by Django 5.2.5 on 2025-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_contactinfo_footerinfo_herosection_importantlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.ImageField(upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon_class',
            field=models.ImageField(upload_to='icon/'),
        ),
    ]
