# Generated by Django 5.2.5 on 2025-08-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_contactinfo_icon_alter_socialmedia_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='icon_class',
            new_name='icon',
        ),
    ]
