# Generated by Django 5.2.5 on 2025-08-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_rename_icon_class_socialmedia_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterInfo',
        ),
    ]
