# Generated by Django 5.2.5 on 2025-08-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_delete_footerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
