# Generated by Django 5.2.5 on 2025-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_delete_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, default='zoopship', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subheading',
            field=models.CharField(blank=True, default='zoopship', max_length=500, null=True),
        ),
    ]
