# Generated by Django 5.2.5 on 2025-08-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_banner_heading_banner_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
    ]
