# Generated by Django 5.2.5 on 2025-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_banner_end_date_remove_banner_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
