# Generated by Django 5.2.5 on 2025-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_navigationitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
