# Generated by Django 5.2.5 on 2025-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_navigationitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
