# Generated by Django 5.2.5 on 2025-08-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_blogpost_meta_description_blogpost_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
