# Generated by Django 5.2.5 on 2025-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_banner_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('steps', models.JSONField(blank=True, default=list, null=True)),
                ('layout_type', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('timeline', 'Timeline')], default='horizontal', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('is_active', models.BooleanField(default=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
