# Generated by Django 5.2.5 on 2025-08-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_howitworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howitworks',
            name='layout_type',
        ),
    ]
