# Generated by Django 5.2.5 on 2025-08-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_howitworks_created_by_howitworks_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='howitworks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
