# Generated by Django 5.2.5 on 2025-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_goalvisionmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalvisionmission',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
