# Generated by Django 5.2.5 on 2025-08-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_alter_goalvisionmission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalvisionmission',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
