# Generated by Django 5.2.5 on 2025-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalvisionmission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
