# Generated by Django 5.2.5 on 2025-08-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_goalvisionmission_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalvisionmission',
            options={'verbose_name': 'impression', 'verbose_name_plural': 'impression '},
        ),
    ]
