# Generated by Django 5.2.5 on 2025-08-14 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_alter_goalvisionmission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalVisionMission',
            new_name='impression',
        ),
    ]
