# Generated by Django 5.2.5 on 2025-08-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_rename_goalvisionmission_impression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.AlterModelOptions(
            name='impression',
            options={'verbose_name': 'impression', 'verbose_name_plural': 'impressions'},
        ),
        migrations.AddField(
            model_name='banner',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impression',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='custom_id',
            field=models.CharField(default='abc123', editable=False, max_length=8, unique=True),
        ),
    ]
