# Generated by Django 5.2.5 on 2025-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_delete_herosection_alter_impression_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='howitworks',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
