# Generated by Django 5.2.5 on 2025-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_alter_banner_custom_id_alter_blogpost_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='howitworks',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
