# Generated by Django 5.2.5 on 2025-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_alter_banner_custom_id_alter_blogpost_custom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='id',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='importantlink',
            name='id',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='id',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='banner',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='howitworks',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
