# Generated by Django 5.2.5 on 2025-08-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_remove_banner_id_remove_blogpost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_custom_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navigationitem'),
        ),
    ]
