# Generated by Django 5.2.5 on 2025-08-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_alter_navigationitem_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationitem',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
