# Generated by Django 5.2.5 on 2025-08-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_rename_parent_navigationitem_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navigationitem'),
        ),
    ]
