# Generated by Django 5.2.5 on 2025-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_alter_navigationitem_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='howitworks',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='importantlink',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='impression',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='navigationitem',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='custom_id',
            new_name='id',
        ),
    ]
