# Generated by Django 5.2.5 on 2025-08-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_rename_custom_id_banner_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLink',
        ),
    ]
