# Generated by Django 5.2.5 on 2025-08-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_delete_importantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='content.page'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='content.page'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='content.page'),
        ),
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.page'),
        ),
        migrations.AddField(
            model_name='feature',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.page'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works', to='content.page'),
        ),
        migrations.AddField(
            model_name='impression',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='content.page'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='content.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
