# Generated by Django 5.2.5 on 2025-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_banner_page_blogpost_page_contactinfo_page_faq_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='page',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='page',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='page',
        ),
        migrations.RemoveField(
            model_name='howitworks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='page',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='banners',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.banner'),
        ),
        migrations.AddField(
            model_name='page',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.blogpost'),
        ),
        migrations.AddField(
            model_name='page',
            name='contact_info',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.contactinfo'),
        ),
        migrations.AddField(
            model_name='page',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.faq'),
        ),
        migrations.AddField(
            model_name='page',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.feature'),
        ),
        migrations.AddField(
            model_name='page',
            name='how_it_works',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.howitworks'),
        ),
        migrations.AddField(
            model_name='page',
            name='impressions',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.impression'),
        ),
        migrations.AddField(
            model_name='page',
            name='navigation_items',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.navigationitem'),
        ),
    ]
