# Generated by Django 5.2.5 on 2025-08-18 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_remove_banner_page_remove_blogpost_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='page',
            name='blog_posts',
        ),
        migrations.RemoveField(
            model_name='page',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='page',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='page',
            name='features',
        ),
        migrations.RemoveField(
            model_name='page',
            name='how_it_works',
        ),
        migrations.RemoveField(
            model_name='page',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='page',
            name='navigation_items',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('faq', 'FAQ'), ('blog_post', 'Blog Post'), ('banner', 'Banner'), ('navigation_item', 'Navigation Item'), ('contact_info', 'Contact Information'), ('how_it_works', 'How It Works'), ('impression', 'Impression'), ('feature', 'Feature')], max_length=50)),
                ('object_id', models.CharField(help_text='ID of the related object (FAQ, Blog, etc.)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pages', to='content.section'),
        ),
    ]
