# Generated by Django 5.2.5 on 2025-08-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_remove_section_content_type_remove_section_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
