# Generated by Django 5.2.5 on 2025-08-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_alter_sectionitem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='section', max_length=255, unique=True),
        ),
    ]
