# Generated by Django 5.2.5 on 2025-08-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_alter_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='content.page'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_pages', to='content.section'),
        ),
    ]
