# Generated by Django 5.2.5 on 2025-08-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_alter_pagesection_page_alter_pagesection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
    ]
